# Generated by Django 4.2.8 on 2023-12-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=50)),
                ('short_url', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'long_short_url',
            },
        ),
    ]
